name: Java Bot CI

on:
  push:
    paths:
      - 'bot/**'
  pull_request:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build botApp with Maven
        run: mvn package -pl bot -am -DskipTests=true
      - name: Build botDocker image
        run: |
          cd bot
          docker build -t bot-app:latest .