name: Java Scrapper CI

on:
  push:
    paths:
      - 'scrapper/**'
  pull_request:
    paths:
      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        #distribution: 'temurin'
        cache: maven
    - name: Build scrapperApp with Maven
      run: mvn package -pl scrapper -am -DskipTests=true
    - name: Build scrapperDocker image
      run: |
        cd scrapper
        docker build -t scrapper-app:latest .