version: "3.9"
services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: userDB
      POSTGRES_PASSWORD: userDB_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=userDB
      - --password=userDB_123
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  backend: