global:
  scrape_interval: 15s
#  scrape_timeout: 10s
#  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bot'
    metrics_path: '/metrics'
    static_configs:
#      - targets: ['localhost:8091']
      - targets:  ['host.docker.internal:8091']

  - job_name: 'scrapper'
    metrics_path: '/metrics'
    static_configs:
#      - targets: ['localhost:8090']
      - targets:  ['host.docker.internal:8090']
