/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Chats;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHATS.CHAT_NUMBER</code>.
     */
    public void setChatNumber(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHATS.CHAT_NUMBER</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getChatNumber() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CHATS.USER_NAME</code>.
     */
    public void setUserName(@Nullable String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHATS.USER_NAME</code>.
     */
    @Size(max = 300)
    @Nullable
    public String getUserName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return Chats.CHATS.CHAT_NUMBER;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Chats.CHATS.USER_NAME;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getChatNumber();
    }

    @Override
    @Nullable
    public String component2() {
        return getUserName();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getChatNumber();
    }

    @Override
    @Nullable
    public String value2() {
        return getUserName();
    }

    @Override
    @NotNull
    public ChatsRecord value1(@NotNull Integer value) {
        setChatNumber(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord value2(@Nullable String value) {
        setUserName(value);
        return this;
    }

    @Override
    @NotNull
    public ChatsRecord values(@NotNull Integer value1, @Nullable String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    @ConstructorProperties({ "chatNumber", "userName" })
    public ChatsRecord(@NotNull Integer chatNumber, @Nullable String userName) {
        super(Chats.CHATS);

        setChatNumber(chatNumber);
        setUserName(userName);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Chats value) {
        super(Chats.CHATS);

        if (value != null) {
            setChatNumber(value.getChatNumber());
            setUserName(value.getUserName());
        }
    }
}
