/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Links;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.10"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinksRecord extends UpdatableRecordImpl<LinksRecord>
    implements Record4<Integer, String, OffsetDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS.ID</code>.
     */
    public void setId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS.ID</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LINKS.URL</code>.
     */
    public void setUrl(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000)
    @NotNull
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LINKS.LAST_UPDATE_DATE</code>.
     */
    public void setLastUpdateDate(@NotNull OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>LINKS.LAST_UPDATE_DATE</code>.
     */
    @NotNull
    public OffsetDateTime getLastUpdateDate() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>LINKS.ID_CHAT</code>.
     */
    public void setIdChat(@Nullable Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>LINKS.ID_CHAT</code>.
     */
    @Nullable
    public Integer getIdChat() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Integer, String, OffsetDateTime, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row4<Integer, String, OffsetDateTime, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return Links.LINKS.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Links.LINKS.URL;
    }

    @Override
    @NotNull
    public Field<OffsetDateTime> field3() {
        return Links.LINKS.LAST_UPDATE_DATE;
    }

    @Override
    @NotNull
    public Field<Integer> field4() {
        return Links.LINKS.ID_CHAT;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getUrl();
    }

    @Override
    @NotNull
    public OffsetDateTime component3() {
        return getLastUpdateDate();
    }

    @Override
    @Nullable
    public Integer component4() {
        return getIdChat();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getUrl();
    }

    @Override
    @NotNull
    public OffsetDateTime value3() {
        return getLastUpdateDate();
    }

    @Override
    @Nullable
    public Integer value4() {
        return getIdChat();
    }

    @Override
    @NotNull
    public LinksRecord value1(@NotNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value2(@NotNull String value) {
        setUrl(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value3(@NotNull OffsetDateTime value) {
        setLastUpdateDate(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord value4(@Nullable Integer value) {
        setIdChat(value);
        return this;
    }

    @Override
    @NotNull
    public LinksRecord values(
        @NotNull Integer value1,
        @NotNull String value2,
        @NotNull OffsetDateTime value3,
        @Nullable Integer value4
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksRecord
     */
    public LinksRecord() {
        super(Links.LINKS);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    @ConstructorProperties({"id", "url", "lastUpdateDate", "idChat"})
    public LinksRecord(
        @NotNull Integer id,
        @NotNull String url,
        @NotNull OffsetDateTime lastUpdateDate,
        @Nullable Integer idChat
    ) {
        super(Links.LINKS);

        setId(id);
        setUrl(url);
        setLastUpdateDate(lastUpdateDate);
        setIdChat(idChat);
    }

    /**
     * Create a detached, initialised LinksRecord
     */
    public LinksRecord(ru.tinkoff.edu.java.scrapper.domain.jooq.tables.pojos.Links value) {
        super(Links.LINKS);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setLastUpdateDate(value.getLastUpdateDate());
            setIdChat(value.getIdChat());
        }
    }
}
