name: java_bot_CI

on:
  push:
    branches: [ "main", "hw8" ]
    paths:
      - 'bot/**'
      - 'messages/**'
  pull_request:
    branches: [ "main", "hw8" ]
    paths:
      - 'bot/**'
      - 'messages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build botApp with Maven
        run: mvn package -pl WebContentUpdateService/bot -am -DskipTests=true