name: java_scrapper_CI

on:
  push:
    branches: [ "main", "hw8" ]
    paths:
      - 'scrapper/**'
      - 'messages/**'
      - 'link-parser/**'
  pull_request:
    branches: [ "main", "hw8" ]
    paths:
      - 'scrapper/**'
      - 'messages/**'
      - 'link-parser/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build scrapperApp with Maven
      run: mvn package -pl scrapper -am -DskipTests=true