name: java_scrapper_CI

on:
  push:
    branches: [ "main", "hw8" ]
    paths:
    - 'WebContentUpdateService/scrapper/**'
    - 'WebContentUpdateService/messages/**'
    - 'WebContentUpdateService/link-parser/**'
  pull_request:
    branches: [ "main", "hw8" ]
    paths:
    - 'WebContentUpdateService/scrapper/**'
    - 'WebContentUpdateService/messages/**'
    - 'WebContentUpdateService/link-parser/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/scrapper-app | toLower

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build scrapperApp with Maven
        working-directory: WebContentUpdateService
        run: mvn package -pl scrapper -am -DskipTests=true

      - name: Build scrapperDocker image
        working-directory: WebContentUpdateService/scrapper
#        run: docker build -t scrapper-app:latest .
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push scrapperDocker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: WebContentUpdateService/scrapper
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}