name: Test

on:
  push:
    branches:
      - main
      - hw8
  pull_request:
    branches:
      - main
      - hw8
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Test workflow!"